tcpdump: listening on enx0050b67c1322, link-type EN10MB (Ethernet), capture size 262144 bytes
0 packets captured
0 packets received by filter
0 packets dropped by kernel
run_tcpdump_on_local_machine - start
run_tcpdump_on_local_machine - about to create capture with name:/home/salvador/github/watchman-readout/GUI/traffic_2021-06-02_20:04:49.pcap
run_tcpdump_on_local_machine - end
Traceback (most recent call last):
  File "getPackets.py", line 40, in <module>
    dfTarget0, dfTarget1=process_packet_pulseSweep(capture_file_name,totalWindows,nofChannels)
  File "/home/salvador/github/watchman-readout/GUI/pulse_analysis.py", line 26, in process_packet_pulseSweep
    scapy_cap = rdpcap(filename)
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1117, in rdpcap
    with PcapReader(filename) as fdesc:  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1154, in __call__
    raise Scapy_Exception(
scapy.error.Scapy_Exception: No data could be read!
